# Generated by Django 6.1 on 2026-08-17 19:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Family', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('gender', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن')], max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ticket sales have started'), (2, 'Tickets are sold out'), (3, 'Tickets are available for sale'), (4, 'The concert has been canceled')]),
        ),
        migrations.CreateModel(
            name='ticketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.timemodel')),
                ('userModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.usermodel')),
            ],
        ),
    ]
