# Generated by Django 6.1 on 2026-08-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0002_usermodel_alter_timemodel_status_ticketmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concertmodel',
            old_name='SingerName',
            new_name='singer_name',
        ),
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='timeModel',
            new_name='time_model',
        ),
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='userModel',
            new_name='user_model',
        ),
        migrations.RenameField(
            model_name='timemodel',
            old_name='concertModel',
            new_name='concert_model',
        ),
        migrations.RenameField(
            model_name='timemodel',
            old_name='locationModel',
            new_name='location_model',
        ),
        migrations.RenameField(
            model_name='timemodel',
            old_name='startDateTime',
            new_name='start_datetime',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
