# Generated by Django 6.1 on 2026-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0003_rename_singername_concertmodel_singer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/concert/'),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='ticket_image',
            field=models.ImageField(null=True, upload_to='images/ticket/'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/user/'),
        ),
    ]
