# Generated by Django 6.1 on 2026-08-24 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0004_concertmodel_poster_ticketmodel_ticket_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertmodel',
            options={'verbose_name': 'کنسرت', 'verbose_name_plural': 'کنسرت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'لوکیشن', 'verbose_name_plural': 'لوکیشن\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'verbose_name': 'بلیط', 'verbose_name_plural': 'بلیط\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'سانس', 'verbose_name_plural': 'سانس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Price',
            field=models.FloatField(verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Time',
            field=models.IntegerField(verbose_name='مدت زمان (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/concert/', verbose_name='پوستر کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='singer_name',
            field=models.CharField(max_length=100, verbose_name='نام خواننده'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Address',
            field=models.CharField(max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Capacity',
            field=models.IntegerField(verbose_name='ظرفیت کل'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام سالن/مکان'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Phone',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='amount',
            field=models.IntegerField(verbose_name='تعداد بلیط'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_image',
            field=models.ImageField(null=True, upload_to='images/ticket/', verbose_name='تصویر بلیط'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='time_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.timemodel', verbose_name='سانس مربوطه'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='user_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.usermodel', verbose_name='خریدار (کاربر)'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت سانس'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='concert_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.concertmodel', verbose_name='کنسرت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='location_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.locationmodel', verbose_name='سالن برگزاری'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='تاریخ و ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'شروع فروش بلیط'), (2, 'تکمیل ظرفیت (تمام شده)'), (3, 'در حال فروش (موجود)'), (4, 'کنسرت لغو شده')], verbose_name='وضعیت فروش'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Family',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن')], max_length=6, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/user/', verbose_name='عکس پروفایل'),
        ),
    ]
